from io import BytesIO
import pandas as pd

def models_excel(models):
    bio=BytesIO()
    with pd.ExcelWriter(bio,engine="xlsxwriter") as w:
        overview=[]
        for i,m in enumerate(models,1):
            overview.append({"model":m.name,"family":m.family,"formula":m.formula,**m.metrics})
            m.coef_table.to_excel(w,sheet_name=f"M{i}_coef"[:31],index=False)
            if m.marginal_effects is not None: m.marginal_effects.to_excel(w,sheet_name=f"M{i}_margins"[:31],index=False)
        pd.DataFrame(overview).to_excel(w,sheet_name="Models",index=False)
    return bio.getvalue()

def docx_report(models, title="Econometrics Lab Report"):
    from docx import Document
    d=Document();d.add_heading(title,0);d.add_paragraph("Generated by Econometrics Lab.")
    for m in models:
        d.add_heading(m.name,level=1);d.add_paragraph(f"Family: {m.family}");d.add_paragraph(f"Formula: {m.formula}")
        if m.metrics:
            t=d.add_table(rows=1,cols=2);t.rows[0].cells[0].text="Metric";t.rows[0].cells[1].text="Value"
            for k,v in m.metrics.items():
                cells=t.add_row().cells;cells[0].text=str(k);cells[1].text=f"{v:.5g}" if isinstance(v,(int,float)) else str(v)
        cols=["term","coef","std_err","p_value","ci_low","ci_high","sig"];tab=d.add_table(rows=1,cols=len(cols))
        for j,c in enumerate(cols): tab.rows[0].cells[j].text=c
        for _,r in m.coef_table[cols].iterrows():
            cells=tab.add_row().cells
            for j,c in enumerate(cols):
                v=r[c];cells[j].text=f"{v:.5g}" if isinstance(v,(int,float)) else str(v)
    bio=BytesIO();d.save(bio);return bio.getvalue()

def pdf_report(models,title="Econometrics Lab Report"):
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet
    bio=BytesIO();doc=SimpleDocTemplate(bio,pagesize=landscape(A4),rightMargin=30,leftMargin=30,topMargin=30,bottomMargin=30)
    styles=getSampleStyleSheet();story=[Paragraph(title,styles["Title"]),Spacer(1,12)]
    for m in models:
        story += [Paragraph(m.name,styles["Heading1"]),Paragraph(f"{m.family} — {m.formula}",styles["BodyText"]),Spacer(1,8)]
        data=[["Term","Coef.","SE","p","CI low","CI high","Sig."]]
        for _,r in m.coef_table.iterrows():
            data.append([str(r["term"])[:45],f'{r["coef"]:.4g}',f'{r["std_err"]:.4g}',f'{r["p_value"]:.4g}',f'{r["ci_low"]:.4g}',f'{r["ci_high"]:.4g}',str(r["sig"])])
        table=Table(data,repeatRows=1);table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.lightgrey),("GRID",(0,0),(-1,-1),.25,colors.grey),("FONTSIZE",(0,0),(-1,-1),7),("VALIGN",(0,0),(-1,-1),"TOP")]))
        story += [table,Spacer(1,14)]
    doc.build(story);return bio.getvalue()
